from time import sleep
print(" *  *  *  *  *\n ** ** ** ** **")
sleep(1)
print("|| || || || ||")
sleep(1)
print("==================")
print("H", end="")
sleep(0.5)
print("a",end="")
sleep(0.5)
print("p",end="")
sleep(0.5)
print("p",end="")
sleep(0.5)
print("y",end="")
sleep(0.5)
print(" ", end="")
print("B",end="")
sleep(0.5)
print("i",end="")
sleep(0.5)
print("r",end="")
sleep(0.5)
print("t",end="")
sleep(0.5)
print("h",end="")
sleep(0.5)
print("d",end="")
sleep(0.5)
print("a",end="")
sleep(0.5)
print("y",end="")
sleep(0.5)
print(" ", end="")
print("Ketyyyy <3", end="")
sleep(0.5)
print("")
print("---------------------")
sleep(1)
print("kuku-dzaa!!")
sleep(0.5)
print("!!!!!!!!!!!!!!!!!!!!!")
print(" ")
sleep(0.5)
print("From: Cveti & Kari")